book_title: Families Crisis and Caring
pdf_file: input/families_crisis.pdf
lang: eng
dpi: 400

# Text curat: fundal alb, fără imagini în MD
preprocess: pil_gray          # grayscale simplu, mai prietenos cu fonturi/italic
tess_psm: 6                   # PSM preferat (linia unică), motorul încearcă și 6/3/4
embed_images: none            # NU insera imagini în Markdown
crop_pct: 0.00                # nu tăia marginile (evită să retezi titluri/footere)
low_conf: 60                  # sub 60 => considerăm pagina slabă
min_chars: 80                 # sub 80 caractere => text junk (ignorăm)

split_strategy:
  - page: 1
    type: single
  - page: 2-300
    type: double
